modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="no_forge"
version="1.0.0"
displayName="No Forge Mod"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://minecraftforge.net"
authors="LeviDog99, MCreator"

[[dependencies.no_forge]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




